# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_special_note', models.CharField(blank=True, max_length=220)),
                ('kitchen_prep_capacity', models.PositiveIntegerField(default=15)),
                ('seating_available', models.BooleanField(default=True)),
                ('takeaway_available', models.BooleanField(default=True)),
                ('packaging_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hygiene_score', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_info', to='businesses.business')),
            ],
        ),
    ]
