# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=25)),
                ('vehicle_type', models.CharField(choices=[('EV_SCOOTER', 'Electric Scooter'), ('BIKE', 'Motorcycle'), ('SCOOTER', 'Scooter'), ('BICYCLE', 'Bicycle')], default='EV_SCOOTER', max_length=25)),
                ('vehicle_number', models.CharField(default='KA-19-TT-2026', max_length=30)),
                ('city', models.CharField(default='Mangaluru', max_length=100)),
                ('current_area', models.CharField(default='Hampankatta', max_length=120)),
                ('current_lat', models.FloatField(default=12.8714)),
                ('current_lng', models.FloatField(default=74.8426)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('total_deliveries', models.PositiveIntegerField(default=38)),
                ('today_earnings', models.DecimalField(decimal_places=2, default=Decimal('480.00'), max_digits=8)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('14250.00'), max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING_PARTNER', 'Waiting for Delivery Partner'), ('ASSIGNED', 'Delivery Partner Assigned'), ('PICKED_UP', 'Picked Up from Business'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], db_index=True, default='WAITING_PARTNER', max_length=25)),
                ('pickup_address', models.CharField(max_length=255)),
                ('drop_address', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=1, default=Decimal('2.4'), max_digits=5)),
                ('estimated_mins', models.PositiveIntegerField(default=24)),
                ('delivery_earning', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=7)),
                ('rider_lat', models.FloatField(default=12.915)),
                ('rider_lng', models.FloatField(default=74.858)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliverypartner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
