# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('emoji_flag', models.CharField(default='🇮🇳', max_length=16)),
                ('greeting', models.CharField(default='Welcome to Tasty Tap 👋', max_length=180)),
                ('subheading', models.CharField(default='Discover authentic regional flavors near you.', max_length=280)),
                ('tagline', models.CharField(default='Flavors of the Region', max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('default_city', models.CharField(default='Bengaluru', max_length=100)),
                ('latitude', models.FloatField(default=12.9716)),
                ('longitude', models.FloatField(default=77.5946)),
                ('card_image_url', models.URLField(blank=True, max_length=500)),
                ('illustration_svg', models.CharField(default='coastal_palm', max_length=80)),
                ('popular_dishes_preview', models.CharField(help_text='Comma-separated popular dishes shown on region cards', max_length=400)),
                ('specialties_sections', models.JSONField(blank=True, default=list, help_text='List of regional spotlight titles e.g. ["Mangaluru Specials", "Mysuru Specials"]')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='core_region_slug_7ba879_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegionalBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('spotlight_tag', models.CharField(default='Local Favorite', help_text='Famous Hotels, Local Favorites, Historic Food Places, Trending Cafes, Hidden Gems', max_length=60)),
                ('is_demo_business', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_spotlights', to='businesses.business')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_businesses', to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('icon', models.CharField(default='🍲', max_length=30)),
                ('illustration_url', models.URLField(blank=True, max_length=500)),
                ('badge_label', models.CharField(blank=True, max_length=60)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_categories', to='core.region')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegionalCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('icon', models.CharField(default='🍛', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_signature', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='core.region')),
            ],
            options={
                'unique_together': {('region', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RegionalFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField()),
                ('typical_price', models.DecimalField(decimal_places=2, default=65.0, max_digits=8)),
                ('veg_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian')], default='VEG', max_length=20)),
                ('spice_level', models.CharField(default='MEDIUM', max_length=20)),
                ('popular_in_cities', models.CharField(blank=True, max_length=200)),
                ('origin_story', models.TextField(blank=True)),
                ('preparation_style', models.TextField(blank=True)),
                ('regional_significance', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_iconic', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='core.regionalcuisine')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_foods', to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(blank=True, help_text='E.g. Onam Sadhya, Pongal Harvest, Ugadi Special, Mysuru Dasara, Ganesh Chaturthi, Diwali', max_length=100)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(max_length=250)),
                ('coupon_code', models.CharField(default='REGIONAL20', max_length=40)),
                ('discount_percentage', models.PositiveIntegerField(default=20)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='businesses.business')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_offers', to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#B8532A', max_length=30)),
                ('secondary_color', models.CharField(default='#1B5E68', max_length=30)),
                ('accent_color', models.CharField(default='#E69F38', max_length=30)),
                ('background', models.CharField(default='#FDF8F2', max_length=120)),
                ('hero_gradient', models.CharField(default='linear-gradient(135deg, #9E421B 0%, #C86D3B 52%, #8A3916 100%)', max_length=250)),
                ('wave_color', models.CharField(default='#1A5F72', max_length=30)),
                ('hero_image', models.URLField(blank=True, max_length=500)),
                ('hero_secondary_image', models.URLField(blank=True, max_length=500)),
                ('hero_tertiary_image', models.URLField(blank=True, max_length=500)),
                ('logo_variant', models.CharField(default='Tasty Tap Coastal', max_length=100)),
                ('font_style', models.CharField(default="'Playfair Display', Georgia, serif", max_length=100)),
                ('animation_style', models.CharField(default='coastal_wave', help_text='E.g. coastal_wave, coconut_breeze, temple_glow, royal_marigold, spice_burst', max_length=60)),
                ('food_categories', models.JSONField(blank=True, default=list)),
                ('popular_foods', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='core.region')),
            ],
        ),
    ]
