# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessanalytics',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_records', to='businesses.business'),
        ),
        migrations.AlterUniqueTogether(
            name='businessanalytics',
            unique_together={('business', 'date')},
        ),
    ]
