# Generated by Django 6.1.1 on 2026-09-26 08:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(default='🍴', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='businesses/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='businesses/covers/')),
                ('description', models.TextField(default='Welcome to our official Tasty Tap digital storefront! Freshly prepared authentic dishes made with local ingredients.')),
                ('heritage_story', models.TextField(blank=True)),
                ('accent_theme', models.CharField(default='#B8532A', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=25)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('website_url', models.URLField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional_license_ref', models.CharField(blank=True, help_text='Optional trade/food registration reference number (if applicable)', max_length=100)),
                ('id_proof_type', models.CharField(default='Local Shop / Business Identity Reference', max_length=80)),
                ('document_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('owner_name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('business_type', models.CharField(choices=[('SMALL_HOTEL', 'Small Hotel'), ('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('BAKERY', 'Bakery'), ('JUICE_SHOP', 'Juice Shop'), ('TEA_SHOP', 'Tea Shop'), ('CLOUD_KITCHEN', 'Cloud Kitchen'), ('HOME_FOOD', 'Home Food Business'), ('FAST_FOOD', 'Fast Food Center'), ('SWEET_SHOP', 'Sweet Shop'), ('DESSERT_SHOP', 'Dessert Shop'), ('TIFFIN_SERVICE', 'Tiffin Service'), ('CATERING', 'Catering Business'), ('FOOD_TRUCK', 'Food Truck'), ('LOCAL_SELLER', 'Local Food Seller'), ('OTHER', 'Other')], db_index=True, default='RESTAURANT', max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(db_index=True, max_length=120)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pincode', models.CharField(default='575001', max_length=12)),
                ('latitude', models.FloatField(default=12.9141)),
                ('longitude', models.FloatField(default=74.856)),
                ('distance_km', models.DecimalField(decimal_places=1, default=1.8, max_digits=5)),
                ('cuisine', models.CharField(default='South Indian • Coastal • Fast Food', max_length=220)),
                ('opening_time', models.TimeField(default=datetime.time(7, 30))),
                ('closing_time', models.TimeField(default=datetime.time(22, 30))),
                ('delivery_available', models.BooleanField(default=True)),
                ('estimated_delivery_time', models.CharField(default='25–35 min', max_length=40)),
                ('delivery_mins_numeric', models.PositiveIntegerField(default=28)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=199.0, max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=7)),
                ('price_range', models.CharField(default='₹₹', max_length=10)),
                ('dietary_type', models.CharField(choices=[('VEG', 'Pure Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('BOTH', 'Veg & Non-Veg')], db_index=True, default='BOTH', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=25)),
                ('subscription_plan', models.CharField(choices=[('FREE', 'Free Joining Plan (₹0 Registration)'), ('GROWTH', 'Growth Partner Plan (Optional Future Tier)'), ('PREMIUM', 'Premium Spotlight Plan (Optional Future Tier)')], default='FREE', max_length=20)),
                ('joining_cost_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_open_now', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_hidden_gem', models.BooleanField(default=False)),
                ('is_local_favorite', models.BooleanField(default=False)),
                ('is_historic_place', models.BooleanField(default=False)),
                ('is_demo_business', models.BooleanField(default=True)),
                ('rating', models.DecimalField(db_index=True, decimal_places=1, default=4.6, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=18)),
                ('total_orders_completed', models.PositiveIntegerField(default=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
    ]
