# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('core', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='core.region'),
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.businesscategory'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='featured_in_profiles', to='menu.fooditem'),
        ),
        migrations.AddField(
            model_name='businessverification',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['status', 'region'], name='businesses__status_f2caf5_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['business_type', 'status'], name='businesses__busines_b5bc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['city', 'status'], name='businesses__city_461fb3_idx'),
        ),
    ]
