# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('BUSINESS_PARTNER', 'Business Partner'), ('DELIVERY_PARTNER', 'Delivery Partner'), ('ADMIN', 'Admin')], db_index=True, default='CUSTOMER', max_length=25)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('has_chosen_region', models.BooleanField(default=False)),
                ('delivery_location_label', models.CharField(default='Home', max_length=60)),
                ('delivery_city', models.CharField(default='Mangaluru', max_length=100)),
                ('delivery_area', models.CharField(default='MG Road', max_length=120)),
                ('delivery_state', models.CharField(default='Karnataka', max_length=100)),
                ('delivery_lat', models.FloatField(default=12.9141)),
                ('delivery_lng', models.FloatField(default=74.856)),
                ('tasty_points', models.PositiveIntegerField(default=120)),
                ('dark_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Current Location', 'Current Location'), ('Other', 'Other')], default='Home', max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=120)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('pincode', models.CharField(default='575001', max_length=12)),
                ('latitude', models.FloatField(default=12.9141)),
                ('longitude', models.FloatField(default=74.856)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned from Order'), ('REDEEMED', 'Redeemed on Checkout'), ('BONUS', 'Welcome / Promo Bonus')], default='EARNED', max_length=20)),
                ('description', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
