# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage Discount'), ('FLAT', 'Flat ₹ Discount'), ('FREE_DELIVERY', 'Free Delivery')], default='PERCENT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=7)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('149.00'), max_digits=8)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('100.00'), max_digits=7, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('usage_limit', models.PositiveIntegerField(default=500)),
                ('used_count', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='businesses.business')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(max_length=240)),
                ('promo_type', models.CharField(choices=[('DISCOUNT', 'Percentage Discount'), ('COMBO', 'Combo Offer'), ('BOGO', 'Buy 1 Get 1'), ('HAPPY_HOUR', 'Happy Hour'), ('FESTIVAL', 'Festival Special'), ('LUNCH', 'Lunch Offer'), ('WEEKEND', 'Weekend Offer'), ('FREE_DELIVERY', 'Free Delivery Offer')], default='DISCOUNT', max_length=25)),
                ('coupon_code', models.CharField(blank=True, max_length=40)),
                ('discount_percentage', models.PositiveIntegerField(default=20)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('199.00'), max_digits=8)),
                ('festival_tag', models.CharField(blank=True, max_length=80)),
                ('badge_text', models.CharField(default='LIMITED OFFER', max_length=50)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='businesses.business')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='core.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
