# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('icon', models.CharField(default='🍛', max_length=30)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_categories', to='core.region')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('slug', models.SlugField(max_length=190)),
                ('description', models.TextField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('veg_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('EGG', 'Contains Egg')], db_index=True, default='VEG', max_length=15)),
                ('spice_level', models.CharField(choices=[('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('HOT', 'Hot'), ('EXTREME', 'Extreme')], db_index=True, default='MEDIUM', max_length=15)),
                ('meal_course', models.CharField(choices=[('STARTER', 'Starter'), ('MAIN', 'Main Course'), ('SIDE', 'Side / Bread'), ('DRINK', 'Drink / Beverage'), ('DESSERT', 'Dessert / Sweet'), ('BREAKFAST', 'Breakfast / Tiffin'), ('SNACK', 'Snack / Fast Food')], db_index=True, default='MAIN', max_length=20)),
                ('preparation_time', models.PositiveIntegerField(default=20, help_text='Preparation time in minutes')),
                ('calories', models.PositiveIntegerField(default=380)),
                ('ingredients', models.TextField(default='Fresh local spices, herbs, cold-pressed oil, chef signature masala')),
                ('allergens', models.CharField(blank=True, default='None / Check with kitchen for nut traces', max_length=180)),
                ('origin_story', models.TextField(blank=True)),
                ('preparation_style', models.CharField(blank=True, max_length=255)),
                ('regional_significance', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/foods/')),
                ('stock_quantity', models.PositiveIntegerField(default=45)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_coastal_favorite', models.BooleanField(default=False)),
                ('is_healthy', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('order_count', models.PositiveIntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='businesses.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='menu.foodcategory')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='core.region')),
            ],
            options={
                'ordering': ['-is_bestseller', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('SIZE', 'Size'), ('ADDON', 'Add-ons'), ('SPICE', 'Spice Level')], default='ADDON', max_length=20)),
                ('option_name', models.CharField(max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='menu.fooditem')),
            ],
            options={
                'ordering': ['group_type', 'price_delta'],
            },
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['business', 'is_available'], name='menu_foodit_busines_bf0857_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['region', 'is_available'], name='menu_foodit_region__387167_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['veg_type', 'price'], name='menu_foodit_veg_typ_ed832e_idx'),
        ),
    ]
