# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('core', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=25, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=25)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_area', models.CharField(default='MG Road', max_length=120)),
                ('delivery_city', models.CharField(default='Mangaluru', max_length=100)),
                ('delivery_lat', models.FloatField(default=12.918)),
                ('delivery_lng', models.FloatField(default=74.861)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('points_redeemed', models.PositiveIntegerField(default=0)),
                ('points_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('coupon_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup'), ('ASSIGNED', 'Delivery Partner Assigned'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=25)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI (GPay / PhonePe / Paytm)'), ('CARD', 'Credit / Debit Card'), ('NET_BANKING', 'Net Banking'), ('COD', 'Cash on Delivery')], default='UPI', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PAID', max_length=20)),
                ('estimated_delivery_mins', models.PositiveIntegerField(default=28)),
                ('points_earned', models.PositiveIntegerField(default=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=160)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('addon_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customization_details', models.CharField(blank=True, max_length=255)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'status'], name='orders_orde_busines_1a89b8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_orde_custome_413d7d_idx'),
        ),
    ]
