# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(default='CUSTOMER', max_length=25)),
                ('notification_type', models.CharField(choices=[('ORDER', 'Order Update'), ('BUSINESS', 'Business Store Update'), ('DELIVERY', 'Delivery Assignment'), ('OFFER', 'New Offer / Promotion'), ('ADMIN', 'Admin Marketplace Alert')], default='ORDER', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, default='/', max_length=250)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
