# Generated by Django 6.1.1 on 2026-09-26 08:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_tag', models.CharField(default='Because you love authentic regional specialties', max_length=180)),
                ('score', models.FloatField(default=0.95)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_entries', to='menu.fooditem')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_cuisines', models.CharField(default='South Indian, Coastal, Mangalorean, Biryani', max_length=250)),
                ('dietary_preference', models.CharField(choices=[('ANY', 'All Foods'), ('VEG', 'Vegetarian Only'), ('NON_VEG', 'Non-Vegetarian Preferred')], default='ANY', max_length=20)),
                ('spice_preference', models.CharField(default='MEDIUM', max_length=20)),
                ('preferred_budget', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
